# Generated by Django 4.2 on 2024-03-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_slug_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('в процессе', 'process'), ('закончен', 'completed')], max_length=10),
        ),
    ]
