# Generated by Django 4.2 on 2024-03-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pr', 'process'), ('com', 'completed')], default='в процессе', max_length=10),
        ),
    ]
